[global]
twoStepFlag             1
slaveOnly               0
priority1               128
priority2               128
domainNumber            0
clockClass              135
clockAccuracy           0xFE
offsetScaledLogVariance 0xFFFF
free_running            0
freq_est_interval       1
dataset_comparison      ieee1588
maxStepsRemoved         255
logAnnounceInterval     1
logSyncInterval         0
logMinDelayReqInterval  0
announceReceiptTimeout  3
syncReceiptTimeout      0
fault_reset_interval    4
neighborPropDelayThresh 20000000
tx_timestamp_timeout    10
summary_interval        0
kernel_leap             1
clock_class_threshold   135
network_transport       UDPv4
delay_mechanism         E2E
time_stamping           software
